# Generated by Django 2.0.2 on 2018-05-06 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('winner1', models.CharField(max_length=20)),
                ('winner2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ranking', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracket.Group')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('groupA1', models.CharField(default='', max_length=30)),
                ('groupA2', models.CharField(default='', max_length=30)),
                ('groupB1', models.CharField(default='', max_length=30)),
                ('groupB2', models.CharField(default='', max_length=30)),
                ('groupC1', models.CharField(default='', max_length=30)),
                ('groupC2', models.CharField(default='', max_length=30)),
                ('groupD1', models.CharField(default='', max_length=30)),
                ('groupD2', models.CharField(default='', max_length=30)),
                ('groupE1', models.CharField(default='', max_length=30)),
                ('groupE2', models.CharField(default='', max_length=30)),
                ('groupF1', models.CharField(default='', max_length=30)),
                ('groupF2', models.CharField(default='', max_length=30)),
                ('groupG1', models.CharField(default='', max_length=30)),
                ('groupG2', models.CharField(default='', max_length=30)),
                ('groupH1', models.CharField(default='', max_length=30)),
                ('groupH2', models.CharField(default='', max_length=30)),
                ('win1', models.CharField(default='', max_length=30)),
                ('win2', models.CharField(default='', max_length=30)),
                ('win3', models.CharField(default='', max_length=30)),
                ('win4', models.CharField(default='', max_length=30)),
                ('win5', models.CharField(default='', max_length=30)),
                ('win6', models.CharField(default='', max_length=30)),
                ('win7', models.CharField(default='', max_length=30)),
                ('win8', models.CharField(default='', max_length=30)),
                ('win9', models.CharField(default='', max_length=30)),
                ('win10', models.CharField(default='', max_length=30)),
                ('win11', models.CharField(default='', max_length=30)),
                ('win12', models.CharField(default='', max_length=30)),
                ('win13', models.CharField(default='', max_length=30)),
                ('win14', models.CharField(default='', max_length=30)),
                ('champion', models.CharField(default='', max_length=30)),
                ('third', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
