# Generated by Django 2.0.2 on 2018-05-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='bracket.UserGroup'),
        ),
    ]
