# Generated by Django 2.0.2 on 2018-05-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0002_group_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
