# Generated by Django 2.0.2 on 2018-05-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0005_auto_20180511_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loss1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='loss2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
