# Generated by Django 2.0.2 on 2018-05-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0006_auto_20180511_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second',
        ),
    ]
