# Generated by Django 2.0.2 on 2018-05-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0008_auto_20180512_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='prize',
            field=models.CharField(default='The winner will receive a gift card to Chick-Fil-A.', max_length=200),
        ),
    ]
