# Generated by Django 2.0.2 on 2018-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0009_usergroup_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='leader',
            field=models.CharField(default='Not Available', max_length=300),
        ),
    ]
