# Generated by Django 2.0.2 on 2018-05-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0010_usergroup_leader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='group',
            name='winner1',
        ),
        migrations.RemoveField(
            model_name='group',
            name='winner2',
        ),
        migrations.AddField(
            model_name='user',
            name='bracketPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='groupPoints',
            field=models.IntegerField(default=0),
        ),
    ]
